version: '3.7'

services:
  cefabot:
    container_name: cefabot-v4
    image: cefadrom/cefabot-v4
    #    build:
    #      context: .
    #      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - 8000:8000
    env_file:
      - .env
    environment:
      - NODE_ENV=prod
      - DB_URI=mongodb://mongo-cefabot-v4/cefabot-v4
      - STORAGE_PATH=/data/cefabot-v4-storage
      - WEB_PORT=8000
    links:
      - mongodb
    volumes:
    - /data/cefabot-v4/storage:/data/cefabot-v4-storage
    depends_on:
      - mongodb
  mongodb:
    container_name: mongo-cefabot-v4
    image: mongo
    volumes:
      - /data/cefabot-v4/db:/data/db
    ports:
      - 8001:27017
